### ISSUE TITLE
Consider adding anime scrappers

### ISSUE THREAD

**Issue by varemenos** [tknorris/salts#100]
Would you consider adding anime scrappers with a tracker integration similar to trakt.tv like myanimelist, anidb, hummingbird etc? There is an endless supply of anime-streaming websites

**Comment by tknorris** [comment]
The problem with almost all those sites is they use absolute numbering rather than season/episode numbering. It makes matching them up to trakt very hard. I'm not much of an anime person myself, but if someone wants to develop the scrapers for them, I'm open to putting them into a dedicated addon that can be installed along side SALTS.

**Comment by varemenos** [comment]
I'm not aware of anyone that tracks their anime with trakt mostly because of the incompatibility like the issue you mentioned.
You should consider anime as a entity and not track them with trakt but with the trackers I've mentioned above. I believe they all have good APIs for it.

**Comment by tknorris** [comment]
SALTS is a trakt addon. The vision for it is all metadata and folders/items come from trakt. If you want to use metadata, etc. from another site, then SALTS is not the right addon for you.
