### ISSUE TITLE
Resume option

### ISSUE THREAD

**Issue by abhinavkssk** [tknorris/salts#116]
Currently the addon tries to resume even a completely played video.Wouldn't it be better to  change it so that it doesn’t try to resume a video that's completed say more than 90% of its run time?

**Comment by tknorris** [comment]
I left it this way on purpose because there's no harm in having bookmarks for something completed since it won't be watched again and there are times were the 90-99% range might be a bookmark the user actually wants. For example, every now and then I get  a stream for a 42 minute tv show that dies at 40 minutes in which is ~95%.

**Comment by abhinavkssk** [comment]
True. But there's  at least one obvious use case that can be avoided--the bookmark can be deleted after a video has been completely watched as opposed to trying to resume from the last second when played again.
