### ISSUE TITLE
Issues 

### ISSUE THREAD

**Issue by ananias47** [tknorris/salts#140]
Hi i have noticed that on some movies the sources have different movie than the search

Second there is no more  wide view option on my next ep is this kodi issue?? 

Third can u add search by genre in movies and to show the latest by year first 

Thnx again for your great work my friend

**Comment by tknorris** [comment]
1. Read the [FAQ](https://github.com/tknorris/salts/wiki/Frequently-Asked-Questions#how-do-i-correct-the-addon-when-it-has-picked-the-wrong-sources-for-a-tv-show-movie-or-episode)
2. I set the content type for Episodes for MNE now so that might have eliminated that view
3. No, the trakt API doesn't support it.

**Comment by ananias47** [comment]
What is mne can i fix it??? sorry again

**Comment by tknorris** [comment]
MNE = My Next Episodes. I doubt it. It makes more sense for the content type for MNE to be Episodes. If your skin doesn't allow that view for Episodes, then there's really nothing to be done.

**Comment by ananias47** [comment]
In the older version it was ok and i didnt change the skin

**Comment by tknorris** [comment]
Yes, as I said, I changed the content type for MNE....

**Comment by ananias47** [comment]
Can u please re-add itbecause  my tv is in a long distance and i must see all ep to find specific 

Thnx again

**Comment by tknorris** [comment]
Nope, I won't change it back. Other views were added as a result of setting the content type that I and others find useful.
