### ISSUE TITLE
re: Moving SALTS DB to USB

### ISSUE THREAD

**Issue by mygithubuserid** [tknorris/salts#141]
Thanks for the link you provided (Issue #138), and sorry but I'm still missing something. To relocate the SALTS DB to USB I need your help to confirm which directory to move (I'm tipping it's ".Kodi" from the information at your link). It would be a bonus if you can also help me confirm how tell the system about the move ("xbmc_env.properties" from the information at your link).

I'm confused in part because, on a related page (http://kodi.wiki/view/Path_substitution), in Section 2 on the same topic as the link you provided, it says "The userdata folder can't normally be relocated completely, except on Android."

FYI, I'm running OSMC on a Raspberry Pi 2.

**Comment by tknorris** [comment]
I haven't personally used OSMC, but on OpenElec there is a simple process for how to move the whole /storage partition off to a different (aka Flash Drive). If OSMC is a Linux derivative, then you can just symlink the .kodi/userdata/Database directory to somewhere on the Flash Drive. Since I haven't personally used OSMC, I can't directly answer your question other than to say that the salts DB is in .kodi/userdata/Database.
