### ISSUE TITLE
"Updating Subscriptions" bar won't go away!

### ISSUE THREAD

**Issue by JordanLongstaff** [tknorris/salts#155]
Well, it will, but not until you're done watching something. And what's especially annoying is, it remains on the screen while you're watching something.

**Comment by tknorris** [comment]
Post a log.

**Comment by tknorris** [comment]
Closed for lack of response.

**Comment by bastardsandcheats** [comment]
If the issue is just that the notification doesn't go away until it finishes you can close the notification with kodi function
 Dialog.Close(all,true)
`<keymap>
    <global>
        <keyboard>
            <u>Dialog.Close(all,true)</u>
        </keyboard>
    </global>
</keymap>`
in keymap.xml will bind it to the u key, read about the keymap.xml on the kodi wiki
I don't know if you can call it from a favorite but you may be able to do so.
