### ISSUE TITLE
have the option to select a different source if one fails

### ISSUE THREAD

**Issue by djbijo** [tknorris/salts#87]
i i select an episode and i get an error playing, instead of having to hit play again i would expect salts to give back the sources list so i can choose another source.

even better, while on auto-play sources, if the auto-play fails it can autoplay the next source or at least ask.

right now auto-play is unusable if using library integration because if the auto selected source fails you have to go to the addon in order to manually choose another source.

**Comment by tknorris** [comment]
If you are in SALTS, you can use the directory source selection method to be kicked back to the list of sources when playback fails rather than the list of episodes. Unfortunately, Kodi doesn't allow addons to do that (i.e. show their own directory) when in the library.

Auto-play will try the next source if the video lookup fails, but once the video url is passed off to Kodi, there's no way for the addon to do anything because it's not running any more. In fact, we've done a lot of work over the last few months to try and catch sources that will fail before passing them to kodi, but some situations just aren't detectable until Kodi attempts to play them.
