### ISSUE TITLE
Excluded sources feature matches whole string not just part

### ISSUE THREAD

**Issue by DrFunkenbreakz** [tknorris/salts#92]
In exclude sources it appears to only work if a full match is made, and not a part match e.g if allvid is put in excluded souces, allvid.ch is not excluded. If you put allvid.ch, only then is allvid.ch excluded. Found this by looking in debug logs as per your instruction, and doing multiple tests. Other forum is down, so put in here for you instead.

**Comment by tknorris** [comment]
Thanks for putting it here. We're working on the forum, it should be back up ASAP.

On the matching it works the opposite of the way you think it does. The substring match is FROM the exclusion list to the source list, not the other way around.
"allvid.ch" in the exclusion list will exclude both "allivid" and "allvid.ch"
I did it this way because lots of hosters don't include the full domain name in the link on their site. For example, they put "180upload" instead of "180upload.com". So, if you put "180upload.com" in the exclusion list it will filter both.

It's certainly debatable which is the right way to do the substring, but that's the way it is right now.

**Comment by DrFunkenbreakz** [comment]
I think i understand. I take it it matches what ever is in the <a> tag or is it somewhere else? The reason I ask is that on one of the source sites, sometimes the hosting site is truncated to "Cloudyvideos.co.." <<<Notice the two periods. If I put cloudyvideos.com in the exclusion list, its not filtered. The way i take it your plugin willl work is that the user would have to put cloudyvideos.co.. in the exclusion list for it to filter. This would mean that the user would have to check the source code of the website to get the correct match for it to be filtered. If it did a part march on cloudyvideos, then cloudyvideos, cloudyvideos.com, and cloudyvideos.co.. would all match making it easier for the user. Obviously I dont know if matching in this way is harder for you to do, or is a performance problem. Thank you for the plugin anyway. Its amazing!

**Comment by tknorris** [comment]
It matches against the part you see to the right of the quality value when you see the sources list. I've constantly debated which way is best, in the example your mentioned you have to add both cloudyvideos.com and cloudyvideos.co.. to your exclusion list. Conversely though, if you think about the example I gave earlier, if I reversed the logic, then you'd have to add 180upload.com and 180upload in to your exclusion list. So either way, you end up having to add 2 different values into your exclusion list depending on which problem you are trying to solve. From what I've been able to tell, the 180upload problem is more common than the cloudyvideos one.
