### ISSUE TITLE
Year removed from TV show directory name

### ISSUE THREAD

**Issue by JordanLongstaff** [tknorris/salts#94]
SALTS is able to discern between different TV shows with the same name but released in different years. Unfortunately, this distinction does not make its way to Kodi's TV show library. The directory names contain the show's title but not the year, meaning Kodi will not scrape it properly. This problem also affects subscription updates. It does not, however, affect movies.

**Comment by tknorris** [comment]
This done purposely because Kodi's tvdb Scraper won't recognize TV Shows directories that have (XXXX) on the end unless there are multiple versions of that particular TV Show. Since I have no way of knowing which shows have multiple versions, I have to make a choice:
1) Create TV Show folders without (XXXX) on the end, thus allowing Kodi's tvdb scraper to work correctly 90% of the time. At the same time, there is still a work around of doing Folder->Show Information->Refresh to force Kodi to recognize which version of a particular show this folder is for when it's wrong. 

or

2) Create TV Show folders with (XXXX) on the end, and then nearly EVERY TV Show folder will need to be manually set to the correct TV Show in Kodi and I get a million questions from less experienced users on "Why don't my TV Show show up in my library?" and I have to walk those same users through the process of manually associating the TV Show folder with the correct show.

I chose option #1.

**Comment by JordanLongstaff** [comment]
You say that the tvdb scraper doesn't work if (XXXX) is on the end? Weird, because my Kodi doesn't have this problem. It could be that in older versions of Kodi it didn't work, but they've since remedied it.

**Comment by tknorris** [comment]
It still doesn't work. I saw the behaviour just a week ago w/ Mythbusters.

**Comment by JordanLongstaff** [comment]
It could be that SALTS isn't connected to a trakt.tv account. The only problem I have with MythBusters is that "Season 1", "Season 2" etc. are replaced with "Season 2003" and "Season 2004" and so on.

**Comment by tknorris** [comment]
No, it's not that. Even local libraries have always behaved like this all the way back to Eden. Just a couple of months ago I got caught by this issue again because some of my local tv show folders got created with years on the end and none of those shows would scan into my library. However, I just tested it on my dev machine and it worked the way you would want...very strange...

**Comment by tknorris** [comment]
For example, here's a post from one of the .org members about this very problem a couple of months ago: http://forum.kodi.tv/showthread.php?tid=219403&pid=1936975#pid1936975

**Comment by JordanLongstaff** [comment]
That post was actually from about seven months ago (more than "a couple") and Kodi was updated last month. Bottom line is, I'm using Kodi v15.2 and have no problems with years in the folder name. But it's up to you whether or not to make the requisite change.

**Comment by tknorris** [comment]
Hmm, it looks like they made a change a few months ago for tvdb that if the show match fails w/ the year, they throw it away and try again with out the year. Matching is still unreliable. For instance, if I create "The Office (2001)" and "The Office (2005)", the first one should be the UK version and the 2nd one should be the US version, then the first one match the UK version, but the 2nd one also gets added as the UK version since their scraper just throws away the year

**Comment by JordanLongstaff** [comment]
I don't watch The Office, so I don't know about that. I guess I'll try it tomorrow and see what happens.

**Comment by tknorris** [comment]
Assuming this was fixed in the last release of the tvdb scraper that was in July, so it's probably been changed since then. They added it to the gotham repo so it's changed for everyone running gotham and later. Since at least matching won't be broken by years any more, it's probably worth adding them so that you people can have the same show w/ different years in their library. The shows with later release date will still need to be manually matched though.

**Comment by JordanLongstaff** [comment]
OK, I think I see why The Office doesn't scrape correctly. In tvdb, the two shows named "The Office" are called "The Office" and "The Office (US)", not "The Office" and "The Office (2005)". In other words, for that show, they used the country of origin instead of the year.

So, tricky that, but at least it wouldn't be a new problem.

**Comment by tknorris** [comment]
Yeah, I agree. There's nothing negative about including the year now since kodi will throw it away if it doesn't need it. I'll look at adding the years back in a future release.

**Comment by tknorris** [comment]
Beta build pushed to start adding (XXXX) to the tv show folders.
